# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

python:
  - 3.7

os:
  - linux

notifications:
  email: false

install:
  - pip install --quiet -r requirements.txt

script:
  - flake8
  - black --check .
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then coverage run setup.py test; fi
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then coverage run setup.py test --addopts "-v -m 'not notebook'"; fi

after_success:
  - codecov

branches:
  only:
  - master
